# Generated by Django 3.0.2 on 2020-01-30 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('news_title', models.CharField(max_length=500, verbose_name='Назва новини')),
                ('news_text', models.TextField(verbose_name='Текст посту')),
                ('news_publication_date', models.DateTimeField(verbose_name='Дата публікації')),
                ('news_image', models.ImageField(upload_to='news_image')),
            ],
            options={
                'verbose_name': 'Новина',
                'verbose_name_plural': 'Новини',
            },
        ),
    ]
