# Generated by Django 3.0.6 on 2020-05-08 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cards',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_title', models.CharField(max_length=500, verbose_name='Заголовок карточки')),
                ('card_text', models.TextField(verbose_name='Текст карточки')),
                ('card_publication_date', models.DateTimeField(verbose_name='Дата публікації')),
                ('card_image', models.ImageField(blank=True, null=True, upload_to='card_image')),
            ],
            options={
                'verbose_name': 'Карточка',
                'verbose_name_plural': 'Карточки',
            },
        ),
    ]
