# Generated by Django 3.0.6 on 2020-05-06 11:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=500, verbose_name='Назва категорії')),
            ],
            options={
                'verbose_name': 'Категорія',
                'verbose_name_plural': 'Категорії',
            },
        ),
        migrations.CreateModel(
            name='Documents',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('documents_title', models.CharField(max_length=500, verbose_name='Назва документу')),
                ('documents_text', models.TextField(verbose_name='Текст документу')),
                ('documents_publication_date', models.DateTimeField(verbose_name='Дата публікації')),
                ('document', models.FileField(upload_to='documents', verbose_name='Документ')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='documents.Categories')),
            ],
            options={
                'verbose_name': 'Документ',
                'verbose_name_plural': 'Документи',
            },
        ),
    ]
