# Generated by Django 3.0.6 on 2020-06-13 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0003_auto_20200611_1506'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documents',
            name='tags',
            field=models.ManyToManyField(blank=True, to='documents.Tags'),
        ),
    ]
