# Generated by Django 3.0.6 on 2020-06-13 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0004_auto_20200613_1637'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sessions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=30, verbose_name='Номер сесії')),
            ],
            options={
                'verbose_name': 'Сесія',
                'verbose_name_plural': 'Сесії',
            },
        ),
    ]
