# Generated by Django 3.0.6 on 2020-06-13 15:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0005_sessions'),
    ]

    operations = [
        migrations.AddField(
            model_name='documents',
            name='session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='documents.Sessions'),
        ),
    ]
