# Generated by Django 3.0.6 on 2020-05-18 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vacancies',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vacancy_name', models.TextField(verbose_name='Назва вакансії')),
                ('vacancy_number', models.IntegerField(blank=True, null=True, verbose_name='Кількість вакансій')),
                ('vacancy_criterion', models.TextField(blank=True, null=True, verbose_name='Критерії')),
                ('vacancy_salary', models.TextField(blank=True, null=True, verbose_name='Зарплата')),
                ('vacancy_contact', models.TextField(blank=True, null=True, verbose_name='Контактна інформація для звернення')),
                ('vacancy_pulication_date', models.TextField(verbose_name='Дата публікації')),
            ],
            options={
                'verbose_name': 'Вакансії',
                'verbose_name_plural': 'Вакансія',
            },
        ),
    ]
