# Generated by Django 3.0.6 on 2020-06-13 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Appeals',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appeal_mail', models.CharField(max_length=70, verbose_name='Електронна пошта')),
                ('appeal_message', models.TextField(verbose_name='Текст звернення')),
                ('appeal_status', models.BooleanField(default=False, verbose_name='Статус')),
                ('appeal_date', models.DateTimeField(verbose_name='Дата та час відправлення')),
            ],
            options={
                'verbose_name': 'Звернення',
                'verbose_name_plural': 'Звернення',
            },
        ),
    ]
