# Generated by Django 3.0.6 on 2020-06-13 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appeal', '0002_auto_20200613_1340'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appeals',
            name='appeal_mail',
            field=models.CharField(max_length=70, verbose_name='Електронна пошта'),
        ),
    ]
