# Generated by Django 3.0.6 on 2020-06-13 11:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appeal', '0003_auto_20200613_1342'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appeals',
            name='appeal_date',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='Дата та час відправлення'),
        ),
        migrations.AlterField(
            model_name='appeals',
            name='appeal_mail',
            field=models.CharField(default='-', max_length=70, verbose_name='Електронна пошта'),
        ),
        migrations.AlterField(
            model_name='appeals',
            name='appeal_message',
            field=models.TextField(default='-', verbose_name='Текст звернення'),
        ),
        migrations.AlterField(
            model_name='appeals',
            name='appeal_status',
            field=models.BooleanField(default=False, verbose_name='Статус виконання'),
        ),
    ]
