# Generated by Django 3.0.6 on 2020-06-13 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Deputies',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullName', models.CharField(max_length=150, verbose_name='ПІП')),
                ('group', models.CharField(max_length=200, verbose_name='Партія')),
                ('workPlace', models.CharField(max_length=200, verbose_name='Місце роботи')),
                ('position', models.CharField(max_length=75, verbose_name='Посада')),
                ('pollingStation', models.TextField(verbose_name='Виборча дільниця')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='deputies')),
            ],
            options={
                'verbose_name': 'Депутат',
                'verbose_name_plural': 'Депутати',
            },
        ),
    ]
