# Generated by Django 3.0.6 on 2020-06-13 19:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('deputies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Партія')),
            ],
            options={
                'verbose_name': 'Партія',
                'verbose_name_plural': 'Партії',
            },
        ),
        migrations.AlterField(
            model_name='deputies',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='deputies.Group'),
        ),
    ]
