# Generated by Django 3.0.2 on 2020-05-05 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Advertisements',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad_title', models.CharField(max_length=500, verbose_name='Назва оголошення')),
                ('ad_text', models.TextField(verbose_name='Текст оголошення')),
                ('ad_publication_date', models.DateTimeField(verbose_name='Дата публікації')),
                ('ad_image', models.ImageField(blank=True, null=True, upload_to='ad_image')),
            ],
            options={
                'verbose_name': 'Оголошення',
                'verbose_name_plural': 'Оголошення',
            },
        ),
    ]
