# Generated by Django 3.0.6 on 2020-05-08 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertisement', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertisements',
            name='ad_title',
            field=models.CharField(max_length=500, verbose_name='Заголовок оголошення'),
        ),
    ]
