# Generated by Django 3.0.6 on 2020-05-06 16:41

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Photos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ptoto_title', models.CharField(max_length=500, verbose_name='Підпис фотографії')),
                ('photo_publication_date', models.DateTimeField(verbose_name='Дата публікації')),
                ('photo', models.ImageField(blank=True, upload_to='gallery')),
            ],
            options={
                'verbose_name': 'Фотографія',
                'verbose_name_plural': 'Фотографії',
            },
            managers=[
                ('object', django.db.models.manager.Manager()),
            ],
        ),
    ]
