# Generated by Django 3.0.6 on 2020-05-06 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='photos',
            managers=[
            ],
        ),
        migrations.RenameField(
            model_name='photos',
            old_name='ptoto_title',
            new_name='photo_title',
        ),
        migrations.AlterField(
            model_name='photos',
            name='photo',
            field=models.ImageField(upload_to='gallery'),
        ),
    ]
